---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - namespace.yaml
  - serviceaccount.yaml
  - daemonset.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
namespace: logging
configMapGenerator:
  - name: promtail
    files:
      - promtail.yml
secretGenerator:
  - name: loki-secret
    envs:
      - .env.secret
    type: Opaque
